export const ANNOUNCEMENTS_ERROR_NOT_FOUND = "Announcement not found!";
export const ANNOUNCEMENTS_STATUS = {
  DRAFT: "DRAFT",
  PENDING: "PENDING",
  SENDING: "SENDING",
  SENT: "SENT",
  CANCELLED: "CANCELLED",
};
export const ANNOUNCEMENT_RECIPIENTS_TYPE = {
  EMPLOYEE: "EMPLOYEE",
  BASIC_ED: "BASIC_ED",
  HIGHER_ED: "HIGHER_ED",
};
